---
- name: Pull an image
  community.general.docker_image:
    name: dolvladzio/new-frontend
    source: pull
#############################################
- name: Verify the Docker image
  command: docker images dolvladzio/new-frontend
#############################################
- name: Start the docker container
  command: docker run -d -p 3000:3000 dolvladzio/new-frontend
