---
- name: Set full container image path
  set_fact:
    full_image_path: "{{ registry_url }}/{{ container.image }}:{{ container.tag }}"

- name: Get reverse-proxy ansible_host
  set_fact:
    reverse_proxy_host: "{{ hostvars['reverse-proxy'].ansible_host }}"

- name: Combine with common_container_env
  set_fact:
    combined_env: "{{ common_container_env | combine({ containers.frontend.env: reverse_proxy_host }) }}"

- name: Create Docker container
  docker_container:
    name: "{{ container.name }}"
    image: "{{ full_image_path }}"
    state: started
    restart_policy: "{{ container_restart_policy }}"
    ports: "{{ container.ports }}"
    env: "{{ combined_env }}"
    volumes: "{{ container.volumes | default([]) }}"
    pull: yes
