- name: Install Nginx (Debian-based)
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure nginx user exists
  ansible.builtin.user:
    name: nginx
    system: yes
    shell: /usr/sbin/nologin
    create_home: no
    state: present

- name: Start Nginx and enable it on boot
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
    daemon_reload: true

- name: Configure Nginx reverse proxy
  ansible.builtin.template:
    src: nginx_reverse_proxy.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Reload Nginx

- name: Ensure Nginx is running
  ansible.builtin.systemd:
    name: nginx
    state: restarted
