- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Copy Nginx reverse proxy config
  copy:
    src: reverse-proxy.conf
    dest: /etc/nginx/sites-available/frontend
  become: yes

- name: Enable site
  file:
    src: /etc/nginx/sites-available/frontend
    dest: /etc/nginx/sites-enabled/frontend
    state: link
    force: yes
  become: yes

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
  become: yes
