- name: Create deployments from template
  template:
    src: deployment.yaml.j2
    dest: "/tmp/{{ item.name }}-deployment.yaml"
  loop: "{{ deployments }}"

- name: Apply deployments
  shell: kubectl apply -f /tmp/{{ item.name }}-deployment.yaml
  loop: "{{ deployments }}"

- name: Create services from template
  template:
    src: service.yaml.j2
    dest: "/tmp/{{ item.name }}-service.yaml"
  loop: "{{ services }}"

- name: Apply services
  shell: kubectl apply -f /tmp/{{ item.name }}-service.yaml
  loop: "{{ services }}"