- name: Check if k3s is already installed
  stat:
    path: "{{ k3s_binary_path }}"
  register: k3s_installed

- name: Initialize cluster
  shell: curl -sfL {{ k3s_url }} | sh -s - server --write-kubeconfig-mode 644 --cluster-init
  when: inventory_hostname == groups['all'][0] and not k3s_installed.stat.exists

- name: Wait for token to be generated
  wait_for:
    path: "{{ node_token_path }}"
    state: present
  when: inventory_hostname == groups['all'][0]