

namespace: jenkins

controller:
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Welcome to Jenkins kh by admin!"
  admin:
    username: admin
    password: admin

  ingress:
    enabled: true
    hostName: jenkins.classschedule.pp.ua
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - secretName: nginx-hello-tls-secret
        hosts:
          - jenkins.classschedule.pp.ua
  image:
      tag: "2.452.1-jdk17"
