---
# Default cloud provider (can be overridden)
cloud_provider: "aws"  # Options: "aws", "gcp"

aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
aws_region: "{{ lookup('env', 'AWS_REGION') | default('eu-central-1') }}"

# Container registry URLs
registry_urls:
  aws: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
  gcp: "gcr.io/{{ gcp_project_id }}"

# Default AWS settings
aws_account_id: "235852762197"  # Replace with actual account ID

# Default GCP settings
gcp_project_id: "my-project"  # Replace with actual project ID

# Common environment variables for all containers
common_container_env:
  LOG_LEVEL: "info"
  NODE_ENV: "production" 