- name: install pip3
  apt: 
    update_cache: yes
    pkg: 
      - python3-pip 

    state: present

- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 

- name: Copy kubeconfig for root user
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: yes

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ item.name }}"
    api_version: v1
    kind: Namespace
    state: present
  loop: "{{ namespaces }}"
  tags: namespaces

- name: Deploy ConfigMap
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/configmap.yaml.j2"
  loop: "{{ configmaps }}"
  tags:
    - configmap


- name: Deploy Secret
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/secret.yaml.j2"
  loop: "{{ secrets }}"
  tags:
    - secret


- name: Deploy Service
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/service.yaml.j2"
  loop: "{{ services }}"
  tags:
    - service


- name: Deploy Deployment
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/deployment.yaml.j2"
  loop: "{{ deployments }}"
  tags:
    - deployment

