---
- name: Add SSH public keys
  ansible.posix.authorized_key: 
    user: "{{ item.name }}" 
    key: "{{ item.key }}" 
  loop: "{{ admin_users }}"  

- name: Restrict root access
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: PermitRootLogin no

- name: Allow ForwardAgent
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowAgentForwarding'
    line: AllowAgentForwarding yes

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted