- name: Add SSH public keys
  ansible.posix.authorized_key: 
    user: "{{ item.name }}" 
    key: "{{ item.key }}" 
  loop: "{{ admin_users }}"
  when: add_ssh_keys | default("no") == "yes"


- name: Restrict root access
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: PermitRootLogin no

- name: Allow ForwardAgent
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowAgentForwarding'
    line: AllowAgentForwarding yes
  notify: Reload SSH
