---
- name: Configure ForceCommand
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ForceCommand'
    line: 'ForceCommand /bin/false'
    state: present
    create: yes
    backup: yes

- name: Configure PermitTTY
  lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitTTY'
        line: 'PermitTTY no'
        state: present
        create: yes
        backup: yes
