# nginx_vars.yml

nginx_user: "nginx"
worker_processes: "auto"
error_log: "/var/log/nginx/error.log"
pid_file: "/run/nginx.pid"
worker_connections: 1024

log_format_name: "main"
log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'

access_log: "/var/log/nginx/access.log"

sendfile: "on"
tcp_nopush: "on"
tcp_nodelay: "on"
keepalive_timeout: 65
types_hash_max_size: 2048

mime_types_file: "/etc/nginx/mime.types"
default_type: "application/octet-stream"

upstream_name: "backend"
upstream_servers:
  - "35.222.6.134:80"

server:
  listen: 80
  server_name: "35.222.6.134"
  location_path: "/"
  proxy_pass: "http://backend"
  proxy_headers:
    - "Host: $host"
    - "X-Real-IP: $remote_addr"
    - "X-Forwarded-For: $proxy_add_x_forwarded_for"
    - "X-Forwarded-Proto: $scheme"
