---
- name: Install AWS CLI
  hosts: all
  become: true

  pre_tasks:
    - name: Check if unzip is installed
      command: which unzip
      register: unzip_check
      ignore_errors: true

    - name: Install unzip if not present (Debian-based)
      apt:
        name: unzip
        state: present
        update_cache: true
      when:
        - unzip_check.rc != 0
        - ansible_os_family == "Debian"

  roles:
    - role: awscli
      vars:
        awscli_install: true