- name: Configure Bastion Host
  hosts: bastion
  become: true

  vars_prompt:
    - name: add_ssh_keys
      prompt: "Add public keys? (yes/no)"
      private: no

  roles:
    - role: ssh-users
    - role: bastion-restriction


- name: Configure local config file
  hosts: localhost
  become: false

  roles:
    - configure-ssh-config