---
- name: Authenticate to ECR
  hosts: ec2_instances
  become: no
  roles:
    - role: ecr_docker_auth

- name: gcp_auth
  hosts: target
  become: true
  roles:
    - role: gcp-docker-auth
      vars:
        gcp_sa_key_path: "/home/ubuntu/gcp-sa-key.json"
        gcp_registry_domain: "europe-central2-docker.pkg.dev"