---
- name: Deploy Frontend Service
  hosts: frontend
  become: yes
  vars_files:
    - vars_files/containers.json
  roles:
    - role: container_exec
  vars:
    container: "{{ containers.frontend }}"
