---
- name: Install Google Cloud Ops Agent
  hosts: all
  become: true
  roles:
    - gcp-ops-agent

---
- name: Configure reverse proxy
  hosts: reverse-proxy
  become: true
  roles:
    - reverse_proxy

---
- name: Deploy Redis Service
  hosts: redis
  become: true
  vars_files:
    - "{{ config_path }}"
  roles:
    - role: install_packages
    - role: container_exec
  vars:
    container: "{{ containers.redis }}"

---
- name: Deploy Backend Service
  hosts: backend
  become: true
  vars_files:
    - "{{ config_path }}"
  roles:
    - role: install_packages
    - role: awscli
    - role: ecr_docker_auth
    - role: container_exec
  vars:
    container: "{{ containers.backend }}"

---
- name: Deploy Frontend Service
  hosts: frontend
  become: true
  vars_files:
    - "{{ config_path }}"
  roles:
    - role: install_packages
    - role: awscli
    - role: ecr_docker_auth
    - role: container_exec
  vars:
    container: "{{ containers.frontend }}"

---
- name: K3s cluster join
  hosts: public
  become: true
  roles: 
    - k3s_cluster_join

---
- name: Configure GCP Ingress Rules
  hosts: localhost
  gather_facts: false
  roles:
    - role: gcp_firewall
      vars:
        project: lofty-memento-458508-i1
        security_groups:
          - name: k3s-sg
            vpc: lofty-memento-458508-i1
            attach_to: [ "k3s" ]
            ingress:
              - protocol: tcp
                port: 6443
              - protocol: tcp
                port: 22
