# - name: Configure reverse proxy
#   hosts: reverse-proxy
#   become: yes
#   roles:
#     - reverse-proxy

# - name: Deploy Redis Service
#   hosts: redis
#   become: yes
#   vars_files:
#     - ../terraform/config.json
#   roles:
#     - role: install_packages
#     - role: container_exec
#   vars:
#     container: "{{ containers.redis }}" 


# - name: Deploy Backend Service
#   hosts: backend
#   become: yes
#   vars_files:
#     - ../terraform/config.json
#   roles:
#     - role: install_packages
#     - role: awscli
#     - role: ecr_docker_auth
#     - role: container_exec
#   vars:
#     container: "{{ containers.backend }}" 

# - name: Deploy Frontend Service
#   hosts: frontend
#   become: yes
#   vars_files:
#     - ../terraform/config.json
#   roles:
#     - role: install_packages
#     - role: awscli
#     - role: ecr_docker_auth
#     - role: container_exec
#   vars:
#     container: "{{ containers.frontend }}" 

- name: K3s cluster join
  hosts: node-1, node-2, node-3
  become: yes
  roles: 
    - k3s_cluster_join