- name: Initialize K3s on Master
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san {{ tls_san }}" sh -s - server --cluster-init
  args:
      creates: /var/lib/rancher/k3s/server/token
  become: true
  # when: inventory_hostname == master_node

- name: Wait for token
  wait_for:
    # path: /var/lib/rancher/k3s/server/node-token
    host: "{{ master_ip }}"
    port: 6443
    delay: 5
    timeout: 300
  delegate_to: "{{ master_node }}"
  run_once: true
