- block:
    - name: Retrieve token
      slurp:
        src: /var/lib/rancher/k3s/server/token

      register: k3s_token_raw
      run_once: true  
      delegate_to: "{{ master_node }}"

    - name: Set token fact
      set_fact:
      # k3s_token: "{{ (k3s_token_raw.content | b64decode | trim).split('::')[0] }}"
        k3s_token: >-
          {{
            k3s_token_raw.content
               | b64decode
               | trim
               | regex_replace('\s+','')
          }}   
      # k3s_token: "{{ k3s_token_raw.content | b64decode | trim }}"
      run_once: true
      delegate_to: "{{ master_node }}"

  when: inventory_hostname == master_node

# regex_replace('::.*$', '')
# master_node replace cluster_master