#SPDX-License-Identifier: MIT-0
---
# tasks file for gcp-docker-auth
- name: Ensure gcloud is installed
  command: which gcloud
  register: gcloud_check
  failed_when: gcloud_check.rc != 0
  changed_when: false

- name: Authenticate gcloud with service account
  command: >
    gcloud auth activate-service-account --key-file={{ gcp_sa_key_path }}
  register: gcloud_auth
  changed_when: false

- name: Configure Docker to use gcloud as a credential helper for Artifact Registry
  command: >
    gcloud auth configure-docker {{ gcp_registry_domain }} --quiet
  register: docker_auth
  changed_when: false

- name: Show Docker authentication config
  command: cat /home/{{ ansible_user }}/.docker/config.json
  register: docker_config
  changed_when: false

- name: Show success message
  debug:
    msg: "Successfully authenticated Docker to GCP registry {{ gcp_registry_domain }}"
